import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Header />
        <main className="min-h-screen bg-white">
          {children}
        </main>
        <footer className="bg-white border-t border-gray-200 py-4 text-center text-sm text-gray-500">
          © 2026 HousePricingPredictor. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
